### ISSUE TITLE
项目很好，我只本地跑过（对，我是来求壁纸的）

### ISSUE THREAD

**Issue by jamesyangget** [Missyanc/CatVsDog#1]
我建议把配置里的绝对路径全部换成相对路径，便于传播和学习（受虐滑稽）

**Comment by jamesyangget** [comment]
我建议把配置里的绝对路径全部换成相对路径，便于传播和学习（受虐滑稽）

**Comment by jamesyangget** [comment]
> 我建议把配置里的绝对路径全部换成相对路径，便于传播和学习（受虐滑稽）
还有建议添加[requirements.txt](https://raw.githubusercontent.com/jamesyangget/CatVsDog/master/requirements.txt)，(大佬别骂我)

**Comment by Missyanc** [comment]
呜呜呜，其实当然也是用的相对路径好呀，但是我这边不知道怎么回事，一用相对路径就莫名报错，也调不好，就用了绝对路径了

**Comment by Missyanc** [comment]
加上啦。
> 壁纸的话，是pycharm的壁纸吗，我的头像就是啦
